### ISSUE TITLE
CMS: Do all slides have unique IDs?

### ISSUE THREAD

**Issue by benjaminbojko** [bluecadet/thf-av02-mindset#4]
Will each slide (Innovator, Flex, Event) have a unique ID across the entire CMS? E.g., no Innovator would ever have the same ID as a Flex slide, right?

**Comment by pingevt** [comment]
@benjaminbojko That is correct. They will all be nodes, which will all have unique ids. If we want we can also use UUIDs.

**Comment by benjaminbojko** [comment]
Great, thanks for the quick response @pingevt . CC @adielfernandez
